[package]
name = "axum-sandbox"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.2.3"
tokio = {version = "1.11.0", features = ["full"]}